name: Ephemeral Workflow
on:
  pull_request:
    types: [labeled, unlabeled, opened, synchronize, reopened]
  workflow_dispatch:
jobs:
  ephemeral:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'ephemeral')
    steps:
      - name: Push ephemeral environment
        run: |
          echo "Checking out code ${{ github.event.pull_request.number }}"
          echo " Unlabeling ${{ github.event.label.name }}"
          VERSION="pr-${{ github.event.pull_request.number }}"
          echo "Pushing ephemeral environment for version $VERSION"
  cleanup:
    runs-on: ubuntu-latest
    if: github.event.action == 'unlabeled' && github.event.label.name == 'ephemeral'
    steps:
      - name: Remove ephemeral environment
        run: |
          echo "Removing ephemeral environment for PR #${{ github.event.pull_request.number }}"
          VERSION="pr-${{ github.event.pull_request.number }}"
          echo "Ephemeral environment $VERSION removed"
