name: Ephemeral Workflow

permissions:
  pull-requests: write

on:
  pull_request:
    types: [labeled, unlabeled, opened, synchronize, reopened]
  workflow_dispatch:
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup SBT
        #run: echo "Compiling code..."
        uses: WorldOfScala/actions/setup-scala@master
      - name: Compile Code
        uses: WorldOfScala/actions/compile@master

  ephemeral:
    name: Push Ephemeral Environment
    uses: WorldOfScala/actions/.github/workflows/publish-pr.yml@master
