name: Ephemeral Workflow
on:
  pull_request:
  workflow_dispatch:
jobs:
  ephemeral:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'ephemeral')
    steps:
      - name: Push ephemeral environment
        run: |
         echo "Checking out code ${{ github.event.pull_request.number }}"
         VERSION="pr-${{ github.event.pull_request.number }}"
         echo "Pushing ephemeral environment for version $VERSION"
