name: Ephemeral Workflow

permissions:
  pull-requests: write

on:
  pull_request:
    types: [labeled, unlabeled, opened, synchronize, reopened]
  workflow_dispatch:
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup SBT
        #run: echo "Compiling code..."
        uses: WorldOfScala/actions/setup-scala@master
      - name: Compile Code
        uses: WorldOfScala/actions/compile@master


  ephemeral:
    name: Push Ephemeral Environment
    uses: WorldOfScala/actions/.github/workflows/publish-pr.yml@master
    with:
      group_id: "k"
      num_groups: "hello-gh-actions"
    # runs-on: ubuntu-latest
    # needs: compile
    # if: contains(github.event.pull_request.labels.*.name, 'ephemeral')
    # steps:
    #   - name: Push ephemeral environment
    #     run: |
    #       echo "Checking out code ${{ github.event.pull_request.number }}"
    #       echo " Unlabeling ${{ github.event.label.name }}"
    #       VERSION="pr-${{ github.event.pull_request.number }}"
    #       echo "Pushing ephemeral environment for version $VERSION"
    #   - name: Tag PR for ArgoCD
    #     uses: actions-ecosystem/action-add-labels@v1
    #     with:
    #       github_token: ${{ github.token }}
    #       labels: "argocd/review"
