name: Do Not Merge

on:
  workflow_dispatch:
  pull_request:
    types: [synchronize, opened, reopened, labeled, unlabeled]

jobs:
  merge-guard:
    name: Prevent Merging
    runs-on: ubuntu-latest
    steps:
      - name: Check for label
        if: ${{ contains(github.event.*.labels.*.name, 'bug') }}
        run: |
          echo "Pull request is labeled as 'do not merge'"
          echo "This workflow fails so that the pull request cannot be merged"
          exit 1
      - name: Ok
        run: echo "Pull request is not labeled as 'do not merge'"